services:
  host:
    build:
      context: .
      dockerfile: host.Dockerfile
    logging:
      driver: "none"
  control:
    build:
      context: .
      dockerfile: control.Dockerfile
    depends_on:
      - host
    volumes:
      - "../launch_script/:/root/scripts"
    entrypoint: /entrypoint.sh
    #   ["ansible-playbook", "-i", "host", "-u", "root", "/root/scripts/main.yml"]
