mysql_root_password: "your-root-password"
mysql_db: "wpdb"
mysql_user: "wpuser"
mysql_password: "password"
mysql_host: "localhost"
wp_admin_user: "admin"
wp_admin_password: "password"
wp_admin_email: "admin@test.com"
wp_url: "http://34.222.209.154"
wp_title: "Test"