---
- name: Ansible hello world!
  hosts: all
  vars_files:
    - vars/default.yml
  tasks:
    # User creation
    - name: "Ensure wheel group exists"
      group:
        name: wheel
        state: present
    - name: "Create admin user"
      ansible.builtin.user:
        name: admin
        group: wheel
        home: /home/admin
    - name: "Create dev user"
      ansible.builtin.user:
        name: dev
        home: /home/dev
    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    - name: "Add ssh key for admin user"
      authorized_key:
        user: admin
        key: "{{ lookup('file', './id_rsa.pub') }}"
    - name: "Add ssh key for dev user"
      authorized_key:
        user: dev
        key: "{{ lookup('file', './id_rsa.pub') }}"
    # LEMP installation
    - name: "Install NGINX"
      dnf:
        name: nginx
        enablerepo: epel-release
        state: present
    - name: "Install MySQL"
      dnf:
        name: mysql-server
        state: present
    - name: "Install PHP"
      dnf:
        name:
          - php
          - php-mysqlnd
        state: present
    # Configure PHP-FPM
    - name: "Set php-fpm group"
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: "^group"
        line: "group = nginx"
    - name: "Set php-fpm user"
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: "^user"
        line: "user = nginx"
    # Configure NGINX
    - name: "Include sites in nginx config"
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: "^http"
        line: "    include /etc/nginx/sites-enabled/*;"
    - name: Ensure sites-available exists
      file:
        path: /etc/nginx/sites-available
        state: directory
        mode: "777"
    - name: Ensure sites-enabled exists
      file:
        path: /etc/nginx/sites-enabled
        state: directory
        mode: "777"
    - name: Copy site config
      copy:
        src: "files/nginx-wp.conf"
        dest: /etc/nginx/sites-available/wordpress
        mode: "777"
    - name: Activate site
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link
    # Configure MySQL
    - name: Install python
      dnf:
        name: python3
        state: present
    - name: Make sure pymysql is present
      become: true
      pip:
        name: pymysql
        state: present
    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
    # Wordpress
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/"
        remote_src: yes
        creates: "/var/www/wordpress"
    - name: Set ownership
      file:
        path: "/var/www/wordpress"
        state: directory
        recurse: yes
        owner: nginx
        group: nginx
    # LEMP services activation
    - name: "Activate php-fpm"
      service:
        state: started
        enabled: yes
        name: php-fpm
    - name: "Activate NGINX"
      service:
        state: started
        enabled: yes
        name: nginx.service
    - name: "Activate MySQL"
      service:
        state: started
        enabled: yes
        name: mysqld
