---
- name: Ansible hello world!
  hosts: all
  tasks:
    - name: "Ensure wheel group exists"
      group:
        name: wheel
        state: present
    - name: "Create admin user"
      ansible.builtin.user:
        name: admin
        group: wheel
        home: /home/admin
    - name: "Create dev user"
      ansible.builtin.user:
        name: dev
        home: /home/dev
    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    - name: "Add ssh key for admin user"
      authorized_key:
        user: admin
        key: "{{ lookup('file', './id_rsa.pub') }}"
    - name: "Add ssh key for dev user"
      authorized_key:
        user: dev
        key: "{{ lookup('file', './id_rsa.pub') }}"
