---
- name: Wordpress auto-installation
  hosts: all
  vars_files:
    - vars/default.yml
  tasks:
    - name: "Install security patches"
      dnf:
        security: yes
        state: latest
    - name: Enable EPEL Repository on CentOS 8
      dnf:
        name: epel-release
        state: latest
    - name: Install UFW
      dnf:
        name: ufw
        state: present
    # User creation
    - name: "Ensure wheel group exists"
      group:
        name: wheel
        state: present
    - name: "Create admin user"
      ansible.builtin.user:
        name: admin
        group: wheel
        home: /home/admin
    - name: "Create dev user"
      ansible.builtin.user:
        name: dev
        home: /home/dev
    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    - name: "Add ssh key for admin user"
      authorized_key:
        user: admin
        key: "{{ lookup('file', './id_rsa.pub') }}"
    - name: "Add ssh key for dev user"
      authorized_key:
        user: dev
        key: "{{ lookup('file', './id_rsa.pub') }}"
    # LEMP installation
    - name: "Install NGINX"
      dnf:
        name: nginx
        enablerepo: epel-release
        state: present
    - name: "Install MySQL"
      dnf:
        name: mysql-server
        state: present
    - name: "Install PHP"
      dnf:
        name:
          - php
          - php-mysqlnd
        state: present
    - name: Install php-json extension
      dnf:
        name: php-json
        state: present
    # LEMP services activation
    - name: "Activate php-fpm"
      service:
        state: started
        enabled: yes
        name: php-fpm
    - name: "Activate NGINX"
      service:
        state: started
        enabled: yes
        name: nginx.service
    - name: "Activate MySQL"
      service:
        state: started
        enabled: yes
        name: mysqld
    # Configure PHP-FPM
    - name: "Set php-fpm group"
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: "^group"
        line: "group = nginx"
    - name: "Set php-fpm user"
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: "^user"
        line: "user = nginx"
    # Configure NGINX
    - name: Copy Nginx config
      copy:
        src: "files/nginx.conf"
        dest: /etc/nginx/nginx.conf
        mode: "770"
    - name: Delete nginx default website
      file:
        state: absent
        path: /usr/share/nginx/html/
    # Configure MySQL
    - name: Install python
      dnf:
        name: python3
        state: present
    - name: Make sure pymysql is present
      become: true
      pip:
        name: pymysql
        state: present
    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
    # Wordpress
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/"
        remote_src: yes
        creates: "/var/www/wordpress"
    - name: Set up wp-config
      template:
        src: "files/wp-config.php.j2"
        dest: "/var/www/wordpress/wp-config.php"
        mode: "600"
    - name: Set ownership
      file:
        path: "/var/www/wordpress"
        state: directory
        recurse: yes
        owner: nginx
        group: nginx
    - name: Set permissions for directories
      shell: "/usr/bin/find /var/www/wordpress/ -type d -exec chmod 750 {} \\;"
    - name: Set permissions for files
      shell: "/usr/bin/find /var/www/wordpress/ -type f -exec chmod 640 {} \\;"
    # Secure LEMP
    - name: Deactivate PHP functions
      lineinfile:
        path: /etc/php.ini
        regexp: "^disable_functions"
        line: "disable_functions =exec,eval,phpinfo,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source"
    - name: Allow SSH
      ufw:
        proto: tcp
        port: "22"
        rule: allow
    - name: Allow port 80
      ufw:
        proto: tcp
        port: "80"
        rule: allow
    - name: Block all connections
      ufw:
        state: enabled
        direction: incoming
        policy: deny
    # LEMP services activation
    - name: "Restart php-fpm"
      service:
        state: restarted
        name: php-fpm
    - name: "Restart NGINX"
      service:
        state: restarted
        name: nginx.service
    - name: "Restart MySQL"
      service:
        state: restarted
        name: mysqld
