---
- name: LEMP auto-installation
  hosts: all
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
    - name: "Install security patches"
      dnf:
        security: yes
        state: latest
    - name: Enable EPEL Repository on CentOS 8
      dnf:
        name: epel-release
        state: latest
    # LEMP installation
    - name: "Install NGINX"
      dnf:
        name: nginx
        state: present
    - name: "Install PHP"
      dnf:
        name:
          - php
          - php-mysqlnd
        state: present
    - name: Install php-json extension
      dnf:
        name: php-json
        state: present
    - name: Install mysql client
      dnf:
        name: mysql
        state: present
    # LEMP services activation
    - name: "Activate php-fpm"
      service:
        state: started
        enabled: yes
        name: php-fpm
    - name: "Activate NGINX"
      service:
        state: started
        enabled: yes
        name: nginx.service
    # Configure PHP-FPM
    - name: "Set php-fpm group"
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: "^group"
        line: "group = nginx"
    - name: "Set php-fpm user"
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: "^user"
        line: "user = nginx"
    # Configure NGINX
    - name: Copy Nginx config
      copy:
        src: "files/nginx.conf"
        dest: /etc/nginx/nginx.conf
        mode: "770"
    - name: Delete nginx default website
      file:
        state: absent
        path: /usr/share/nginx/html/
    # Configure SELINUX
    - name: Configure SELINUX
      selinux:
        policy: targeted
        state: permissive
    # Secure LEMP
    - name: Deactivate PHP functions
      lineinfile:
        path: /etc/php.ini
        regexp: "^disable_functions"
        line: "disable_functions =exec,eval,phpinfo,passthru,shell_exec,system,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source"
    # LEMP services activation
    - name: "Restart php-fpm"
      service:
        state: restarted
        name: php-fpm
    - name: "Restart NGINX"
      service:
        state: restarted
        name: nginx.service
    # Create wordpress directory
    - name: Create wordpress directory
      file:
        state: directory
        path: /var/www/wordpress
    # Download WP-CLI
    - name: Download wp-cli
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: 0755